### ISSUE TITLE
How do I customize the generation rules?

### ISSUE THREAD

**Issue by rainedAllNight** [quicktype/quicktype-xcode#10]
How do I customize the generation rules?

**Comment by dvdsgl** [comment]
You can't within Xcode at the moment, but you can download our CLI or use https://app.quicktype.io

How would you like to customize them?

**Comment by rainedAllNight** [comment]
I am using the framework named ObjectMapper, and I want to generate code that works for it.

**Comment by dvdsgl** [comment]
Ah, very good.

We have some prelimary work to let you customize the output using handlebars but it's very prelimary. You can find an option for this in our CLI.

Another option is to actually change https://GitHub.com/quicktype/quicktype to add an option to do what you want. This is your best route for now. Would you mind filing an issue on that repo with some sample code for what you'd like the output to look like?

**Comment by rainedAllNight** [comment]
Ok，Here's a simple example.

`struct VehicleBrandModel {
    var brandName: String = ""
    var brandPy: String = ""
    var brandImage: URL?
}

extension VehicleBrandModel: Mappable {
    init?(map: Map) {
        
    }
    
    mutating func mapping(map: Map) {
        brandName  <- map["brand_name"]
        brandPy    <- map["brand_py"]
        brandImage <- (map["brand_img"], URLTransform())
    }
}`

**Comment by rainedAllNight** [comment]
Do you mean Codeable?

**Comment by dvdsgl** [comment]
Yes. 😄

**Comment by rainedAllNight** [comment]
I found that it had some defects in a particular structure and type. so I keep using ObjectMapper now

**Comment by dvdsgl** [comment]
Would you mind sharing what those defects are? We'd like to add them to our tests, or help generate a workaround without requiring you to abandon Codables.

**Comment by rainedAllNight** [comment]
And In any case, is it always a more friendly way to support a custom🙂

**Comment by dvdsgl** [comment]
Alright, we have an upstream issue for this: https://github.com/quicktype/quicktype/issues/223

**Comment by rainedAllNight** [comment]
ok, thanks
