### ISSUE TITLE
App window is empty

### ISSUE THREAD

**Issue by barrypress** [quicktype/quicktype-xcode#11]
I installed quicktype yesterday, and when it started it had the normal window looking much like the web site, and the Xcode integration worked (albeit I can't see a way to change preferences for what it does within Xcode). I then closed quicktype, leaving Xcode running.

This morning, it still works from within Xcode, but opening the app results in a completely blank window. Lots of white pixels, nothing else. Paste is disabled.

**Comment by dvdsgl** [comment]
@barrypress sorry to hear this – the app is obviously just a simple web view hosting https://app.quicktype.io. It is an offline app that should still be cached and work without a connection, which makes it extra puzzling that it worked before but not subsequently.

Can you try reopening the app while connected to the Internet?

**Comment by dvdsgl** [comment]
And by "paste is disabled" do you mean that the Xcode extension menu is disabled?

Unfortunately Xcode extensions cannot display any UI in Xcode itself, so the `Paste JSON as Code` feature is pretty limited.

**Comment by barrypress** [comment]
No, this was all in the application as launched separately. 

Do I perhaps mis-understand and it isn’t supposed to run separately? (Odder yet, I ran it just now and it came up fine. Fortunately, *my* code is never erratic. Yup, bank on that. Right. Er…)

All in all, I think it’s a great capability, and if I knew how to set options for it I’d be a happy camper. Perhaps if the preference settings in the app carried over into the extension?

Thanks

Barry

---
"They laughed at Columbus, they laughed at Fulton, they laughed at the Wright Brothers. But they also laughed at Bozo the Clown." - Carl Sagan
