### ISSUE TITLE
Spruce up the macOS app

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype-xcode#2]
Here's what you currently see when you launch the app:

![image](https://user-images.githubusercontent.com/108197/34469900-f84ca8cc-eedb-11e7-8da9-7eca8edf4b22.png)

We should at least show a message and icon here, a note about the Xcode plugin, links to GitHub and our homepage, etc.

Better yet, we could bundle an offline build of app.quicktype.io.

**Comment by schani** [comment]
Why is there an app in the first place?  Is that required for some weird reason?

**Comment by dvdsgl** [comment]
Yes, the app is required to host the Xcode extension.

**Comment by dvdsgl** [comment]
Added a dialog with some instruction:

![image](https://user-images.githubusercontent.com/108197/34498014-9845fc1a-efb4-11e7-9c3f-0069d0f5a485.png)

**Comment by Narek1994** [comment]
Hi

I have enabled quicktype for xcode, but when I select en copy json paste json as always disabled
