### ISSUE TITLE
Lower deployment target to macOS 10.12

### ISSUE THREAD

**Issue by BenchR267** [quicktype/quicktype-xcode#4]
Is there any reason why this needs 10.13. to be the deployment target? Would love to use it… with 10.12. and Xcode 9..

**Comment by dvdsgl** [comment]
Fixed in PR #5

**Comment by dvdsgl** [comment]
@BenchR267 [here's a build](https://install.appcenter.ms/orgs/quicktype/apps/quicktype-xcode/distribution_groups/xcode%20testers) that targets 10.12 – can you please try it? You may have top open it by right-clicking in Finder and choosing `Open` since it's not signed.

**Comment by BenchR267** [comment]
I actually just updated to High Sierra 🙈 But I can check it on Monday on my work machine and let you know! Thanks anyway for the fast reponse!

**Comment by dvdsgl** [comment]
Leaving open for confirmation.

**Comment by BenchR267** [comment]
@dvdsgl was able to test it now with Sierra and it works like a charm! 👌

**Comment by dvdsgl** [comment]
Thanks! Will upload to the App Store soon.
