### ISSUE TITLE
Objective-C support

### ISSUE THREAD

**Issue by ShannonChenCHN** [quicktype/quicktype-xcode#7]
It's really a convenient tool! 

But I found that [converting JSON to Objective-C is not supported](https://app.quicktype.io). There are lots of developers still using Objective-C throughout the world. So why not?

**Comment by dvdsgl** [comment]
I was wondering yesterday whether we should offer first-class Objective-C support. There's no good reason not to, but we are an open-source project looking for contributors so we'd love a passionate Objective-C user to help us out here!

We support Objective-C++ via our C++ target language, and you can mix Swift and Objective-C in the save project for now.

**Comment by dvdsgl** [comment]
If anyone is interested in contributing Objective-C support, our main library is [quicktype/quicktype](https://github.com/quicktype/quicktype) so you can clone our core service there, and begin working on Objective-C support.

**Comment by dvdsgl** [comment]
I've started to play with Objective-C support in the quicktype core project: https://github.com/quicktype/quicktype/pull/429

Please subscribe and give feedback as it starts to take shape!

**Comment by dvdsgl** [comment]
@ShannonChenCHN Here is an early prototype: https://app2.quicktype.io/#l=objc

Can you give me some feedback on the generated code? Is this what you'd expect?

**Comment by dvdsgl** [comment]
Now available: https://app.quicktype.io/#l=objc

Will upload an updated extension to the App Store soon

**Comment by ShannonChenCHN** [comment]
@dvdsgl Wow, Can't imagine the Objective-C version come into reality so quickly👏. 

After using some features on https://app.quicktype.io/#l=objc, I found that：
- some generated Objective-C doesn't follow the standard Objective-C grammar. 
- I can't change the content properly in `class prefix` input field.

I figure out that you probably aren't familiar with Objective-C grammar. As I know, there is a Mac desktop App similar to this project, called [JSONExport](https://github.com/Ahmed-Ali/JSONExport). Wish this could help you to make it better.

I'll ask some other developers I know if they would like to make any contributions.

ps: Sorry for being this late to reply :-).

**Comment by dvdsgl** [comment]
* Would you mind pointing out where it deviates from the standard grammar? It will take me hours of study to learn what this means, but if you can just tell me, I can fix it in seconds.
* You cannot change the `class prefix` field at all? What browser are you using?

Thanks for trying it!

**Comment by ShannonChenCHN** [comment]
When [define a Objective-C class](https://developer.apple.com/library/content/documentation/General/Conceptual/DevPedia-CocoaCore/ClassDefinition.html#//apple_ref/doc/uid/TP40008195-CH6-SW2), we have to define interface part and implementation part.

As for me, I think it would be easier to implement JSON->Obj-C converting if we only consider the basic needs.

1. For `implementation` part, it's ok to leave it empty:

```
@implementation MyObject

@end
```

2. Basically, we only need to take care of the properties in class *interface*.

This is what a standard [Objective-C class's property](https://developer.apple.com/library/content/documentation/General/Conceptual/DevPedia-CocoaCore/DeclaredProperty.html#//apple_ref/doc/uid/TP40008195-CH13-SW1) looks like:
`@property (<#attributes#>) <#type#> <#name#>;`

So we need to define proper attributes and type for a property.
> For property name, alphabetic character is recommended. 

①. instance type 
According to Apple's [documentation](https://developer.apple.com/library/content/documentation/General/Conceptual/DevPedia-CocoaCore/ModelObject.html#//apple_ref/doc/uid/TP40008195-CH31-SW1), instance variables can be objects, scalar values.

② attribute 
The attribute for a property normally corresponds to the property's type. See [this](http://www.ios-blog.co.uk/tutorials/objective-c/objective-c-property-attribute-reference-guide/) for more information.

#### Examples
So when we define a custom model object, we would meet the following 3 type of instance variables:

- scalar values
```
@property (nonatomic, assign) NSInteger age;
@property (nonatomic, assign) float weight;
```

- Objective-C object defined by Foundation 
```
@property (nonatomic, strong) NSString * greeting;
@property (nonatomic, strong) NSArray * instructions;
```

- Custom Objective-C object 
```
@property (nonatomic, strong) Person * father;
```

Let's see what a template JSON text should be converted.

JSON text:
```
{
  "greeting": "Welcome to quicktype!",
  "instructions": [
    "Type or paste JSON here",
    "Or choose a sample above",
    "quicktype will generate code in your",
    "chosen language to parse the sample data"
  ],
  "count": 26,
  "price": 102.5,
  "detail": {
	"name": "banana",
	"weight": 20.0
  }
}
```
Objective-C Code:

```
#import <Foundation/Foundation.h>
#import "Detail.h"

@interface RootClass : NSObject

@property (nonatomic, assign) NSInteger count;
@property (nonatomic, strong) Detail * detail;
@property (nonatomic, strong) NSString * greeting;
@property (nonatomic, strong) NSArray * instructions;
@property (nonatomic, assign) float price;

@end
```
```
#import "RootClass.h"

@implementation RootClass
@end
```

```
#import <Foundation/Foundation.h>
@interface Detail : NSObject

@property (nonatomic, strong) NSString * name;
@property (nonatomic, assign) float weight;

@end
```

```
#import "Detail.h"

@implementation RootClass
@end
```

**Comment by ShannonChenCHN** [comment]
I used safari to open https://app.quicktype.io/#l=objc. 😂

**Comment by dvdsgl** [comment]
Yes, I need to understand the property attributes better and implement them more carefully.

I agree that we should marshal the `NSNumber*` instances returned from `NSJSONSerialization` to primitive types, although this will take some special care around `NSArray` and `NSDictionary` that contain these primitive values, but for model classes, this should be achievable.

Unfortunately, a little more than this is required when marshaling from the dynamic JSON values. For example, I need some method or function to pluck the properties out of the `NSDictionary` returned by the JSON deserializer. It's not an option to simply omit that, otherwise the properties never get assigned. Or did I misunderstand?

**Comment by ShannonChenCHN** [comment]
1. Convert numerical value to `NSNumber *` type is acceptable.

2. Good, I see it. `Types only` is exactly I need. The property assignment depends on how we transform JSON dictionary to model object. if we use some 3rd-party frameworks, like Mantle, YYModel, JSONModel, we don't need to get every property assigned by writing assign code directly, because Objective-C has runtime feature(It's different for Swift).

3.  It it not necessary to write `@synthesize ` code explicitly anymore in most cases, since modern clang compiler has autosynthesis of properties for Objective-C.

**Comment by dvdsgl** [comment]
Yay! That’s great news about synthesize.

Also, if you want to contribute, it would be great to add support for Mantle, etc.
