### ISSUE TITLE
Can't find Paste JSON

### ISSUE THREAD

**Issue by dkao1222** [quicktype/quicktype-xcode#8]
Has goto extension but not find "Paste JSON as" in Xcode's Editoe menu  only find "quickType", apps always alert need me to enable extension.

**Comment by dvdsgl** [comment]
Did you enable quicktype in `System Preferences > Extensions`?

![image](https://user-images.githubusercontent.com/108197/34681671-747e4386-f451-11e7-936f-8e92c8642ea9.png)

**Comment by dkao1222** [comment]
Sorry, I has found the function in Xcode's and confirm extension is work.

**Comment by dvdsgl** [comment]
Victory! Enjoy it.
